from collections import defaultdict
from dataclasses import dataclass, field
from itertools import pairwise

import numpy as np

from img2table.tables.objects.cell import Cell


@dataclass
class ItemHolder:
    items: list[Cell] = field(default_factory=list, repr=False)

    @property
    def x1(self) -> int:
        return min((it.x1 for it in self.items), default=0)

    @property
    def y1(self) -> int:
        return min((it.y1 for it in self.items), default=0)

    @property
    def x2(self) -> int:
        return max((it.x2 for it in self.items), default=0)

    @property
    def y2(self) -> int:
        return max((it.y2 for it in self.items), default=0)

    @property
    def width(self) -> int:
        return self.x2 - self.x1

    @property
    def height(self) -> int:
        return self.y2 - self.y1

    @property
    def area(self) -> int:
        return self.width * self.height


@dataclass
class Whitespace:
    start: int
    end: int
    start_bound: bool = False
    end_bound: bool = False

    @property
    def width(self) -> int:
        return self.end - self.start

    def matching_bound(self, other: "Whitespace") -> bool:
        if self.start_bound and other.start_bound:
            return True
        return self.end_bound and other.end_bound

    def __hash__(self) -> int:
        return hash((self.start, self.end, self.start_bound, self.end_bound))


@dataclass
class MergedRow(ItemHolder):
    _ws_cache: dict[tuple[float, int], list[Whitespace]] = field(default_factory=dict)

    def add(self, item: Cell) -> None:
        self.items.append(item)

    @property
    def y_center(self) -> float:
        return (self.y1 + self.y2) / 2

    def compute_whitespaces(self, min_width: float, width: int) -> list[Whitespace]:
        """
        Compute whitespaces between cells in a merged row.
        :param min_width: minimum width for a whitespace to be considered
        :param width: total width of the row
        :return: list of whitespaces
        """
        cache_key = (min_width, width)
        if cache_key in self._ws_cache:
            return self._ws_cache[cache_key]

        # Compute whitespaces
        self._ws_cache[cache_key] = compute_whitespaces(
            items=self.items, min_width=min_width, width=width
        )
        return self._ws_cache[cache_key]


@dataclass
class ColumnSection(ItemHolder):
    rows: list[MergedRow] = field(default_factory=list, repr=False)
    whitespaces: list[Whitespace] = field(default_factory=list)

    def update(self, row: MergedRow, whitespaces: list[Whitespace]) -> "ColumnSection":
        self.items += row.items
        self.rows += [row]
        self.whitespaces = whitespaces

        return self

    @property
    def nb_columns(self) -> int:
        return max(0, len(self.whitespaces) - 1)

    @property
    def first_y_center(self) -> float:
        return min((row.y_center for row in self.rows), default=0)

    @property
    def last_y_center(self) -> float:
        return max((row.y_center for row in self.rows), default=0)

    def sanitize(self, min_width: float, width: int) -> "ColumnSection":
        """
        Sanitize whitespaces by removing ones generated by a single row.
        :param min_width: minimum width for a whitespace to be considered
        :param width: total width of the section
        :return: self
        """
        # Sort rows by Y-position
        self.rows.sort(key=lambda row: row.y1)

        if len(self.rows) < 2:
            return self

        single_matching_ws = defaultdict(int)
        for row in self.rows:
            row_ws = row.compute_whitespaces(min_width=min_width, width=width)
            for r_ws in row_ws:
                # For each row whitespace, find matching section whitespaces
                matching_ws = [
                    ws for ws in self.whitespaces if r_ws.start <= ws.start and r_ws.end >= ws.end
                ]

                # If the row whitespace matches exactly one section whitespace, increment the count
                if len(matching_ws) == 1:
                    single_matching_ws[matching_ws.pop()] += 1

        # Keep bound whitespaces and those that are matched by multiple rows
        self.whitespaces = [
            ws
            for ws in self.whitespaces
            if ws.start_bound or ws.end_bound or single_matching_ws[ws] > 1
        ]
        return self


@dataclass
class RowCharacteristic:
    index: int
    row: MergedRow
    ws: list[Whitespace]

    @property
    def count(self) -> int:
        return len(self.ws)

    @property
    def inner_ws_width(self) -> int:
        inner_ws = [ws for ws in self.ws if not ws.start_bound and not ws.end_bound]
        return sum(ws.width for ws in inner_ws) if inner_ws else 0


def compute_whitespaces(items: list[Cell], min_width: float, width: int) -> list[Whitespace]:
    """
    Compute whitespaces between cells.
    :param items: list of cells
    :param min_width: minimum width for a whitespace to be considered
    :param width: total width of the row
    :return: list of whitespaces
    """
    current_x, whitespaces = 0, []
    for item in sorted(items, key=lambda it: it.x1):
        # Check gap width
        gap = item.x1 - current_x
        if current_x == 0 or gap >= min_width:
            whitespaces.append(Whitespace(start=current_x, end=item.x1, start_bound=current_x == 0))
        current_x = max(current_x, item.x2)

    # Add last whitespace
    whitespaces.append(Whitespace(start=current_x, end=width, end_bound=True))

    return whitespaces


def identify_merged_rows(cnts: list[Cell]) -> list[MergedRow]:
    """
    Identify merged rows in a list of cells.
    :param cnts: list of cells
    :return: list of merged rows
    """
    if not cnts:
        return []

    current_row, merged_rows = None, []
    for cnt in sorted(cnts, key=lambda cnt: (cnt.y1, cnt.x1)):
        if current_row is None:
            current_row = MergedRow(items=[cnt])
            continue

        # Compute overlap
        overlap = min(current_row.y2, cnt.y2) - max(current_row.y1, cnt.y1)
        if overlap <= 0.33 * min(cnt.height, current_row.height):
            # Flush current row
            merged_rows.append(current_row)
            current_row = MergedRow()
        current_row.add(cnt)

    # Add last row
    merged_rows.append(current_row)

    return merged_rows


def matching_whitespaces(
    ws1_list: list[Whitespace], ws2_list: list[Whitespace], min_width: float
) -> tuple[bool, list[Whitespace]]:
    """
    Identify if both sets of whitespaces match
    :param ws1_list: first set of whitespaces
    :param ws2_list: second set of whitespaces
    :param min_width: minimum column width
    :return: boolean indicating whether two sets of whitespaces match and resultant whitespaces
    """
    # Get largest and smallest list of whitespaces and iterate over the shortest list
    ws_short, ws_long = (
        (ws1_list, ws2_list) if len(ws1_list) <= len(ws2_list) else (ws2_list, ws1_list)
    )

    matching_ws, covered_long_indices = [], set()
    for ws_s in ws_short:
        found_matching_ws = False
        for idx, ws_l in enumerate(ws_long):
            # Compute overlap
            overlap = min(ws_s.end, ws_l.end) - max(ws_s.start, ws_l.start)

            # Check overlap is sufficient or if bounds match
            if overlap >= 0.8 * min(ws_s.width, ws_l.width, 0.5 * min_width) or ws_s.matching_bound(
                ws_l
            ):
                matching_ws.append(
                    Whitespace(
                        start=max(ws_s.start, ws_l.start),
                        end=min(ws_s.end, ws_l.end),
                        start_bound=ws_s.start_bound and ws_l.start_bound,
                        end_bound=ws_s.end_bound and ws_l.end_bound,
                    )
                )
                covered_long_indices.add(idx)
                found_matching_ws = True

        if not found_matching_ws:
            return False, []

    if len(covered_long_indices) < len(ws_long):
        return False, []

    return True, sorted(matching_ws, key=lambda x: x.start)


def ensure_section_bounds_consistency(
    section: ColumnSection, min_width: float, width: int
) -> list[ColumnSection]:
    """
    Check that top / bottom elements of the column section are consistent with its correspondence
    :param section: Column section to check.
    :param min_width: minimum width for a whitespace to be considered
    :param width: total width of the row
    :return: List of consistent column sections.
    """
    if section.nb_columns < 2 or len(section.rows) < 2:
        return [section]

    # Identify core elements (with at least 2 columns)
    rows: list[MergedRow] = sorted(section.rows, key=lambda x: x.y1)
    core_indices = [
        i for i, r in enumerate(rows) if len(r.compute_whitespaces(min_width, width)) > 2
    ]

    # Only one row with columns: split the section into multiple sections
    if len(core_indices) < 2:
        return [ColumnSection().update(r, r.compute_whitespaces(min_width, width)) for r in rows]

    # Compute median row separation in core rows
    row_gaps = [
        nxt.y_center - prv.y_center
        for prv, nxt in pairwise(rows[min(core_indices) : max(core_indices) + 1])
    ]
    threshold = 1.5 * np.median(row_gaps)

    # Identify if top elements are coherent with core rows
    top_split_idx: int | None = None
    for i in range(min(core_indices) - 1, -1, -1):
        if abs(rows[i + 1].y_center - rows[i].y_center) > threshold:
            top_split_idx = i
            break

    # Identify if bottom elements are coherent with core rows
    bottom_split_idx: int | None = None
    for i in range(max(core_indices) + 1, len(rows)):
        if abs(rows[i].y_center - rows[i - 1].y_center) > threshold:
            bottom_split_idx = i
            break

    # Identify core section delimiters
    core_start = top_split_idx + 1 if top_split_idx is not None else 0
    core_end = bottom_split_idx if bottom_split_idx is not None else len(rows)

    # Create core rows section
    core_rows = rows[core_start:core_end]
    core_section = ColumnSection(
        items=[it for r in core_rows for it in r.items],
        rows=core_rows,
        whitespaces=compute_whitespaces(
            [it for r in core_rows for it in r.items], min_width, width
        ),
    )

    # Create top and bottom sections
    top_sections = [
        ColumnSection().update(row, row.compute_whitespaces(min_width, width))
        for row in rows[:core_start]
    ]
    bottom_sections = [
        ColumnSection().update(row, row.compute_whitespaces(min_width, width))
        for row in rows[core_end:]
    ]

    return [*top_sections, core_section, *bottom_sections]


def assess_table_whitespace_coherency(
    list_ws_1: list[Whitespace],
    list_ws_2: list[Whitespace],
    vertically_close: bool,
) -> bool:
    """
    Assess whether the whitespaces of 2 sections are coherent.
    :param list_ws_1: Set of whitespaces from first section.
    :param list_ws_2: Set of whitespaces from second section.
    :param min_width: Minimum width for a whitespace to be considered significant.
    :param vertically_close: Whether the two sections are vertically close.
    :return: True if the whitespaces are coherent, False otherwise.
    """
    # Single column case
    if min(len(list_ws_1), len(list_ws_2)) < 3:
        return vertically_close & (len(list_ws_1) == len(list_ws_2))

    ws_short, ws_long = (
        (list_ws_1, list_ws_2) if len(list_ws_2) > len(list_ws_1) else (list_ws_2, list_ws_1)
    )
    # Check whitespaces coherency on "middle" whitespaces
    ws_overlap_width = sum(
        max(
            (
                overlap
                for ws_s in ws_short
                if (overlap := max(0, min(ws_l.end, ws_s.end) - max(ws_l.start, ws_s.start)))
                >= 0.75 * min(ws_l.width, ws_s.width)
            ),
            default=0,
        )
        for ws_l in ws_long
    )

    # Compute threshold for coherency
    if min(len(list_ws_1), len(list_ws_2)) < 4:
        threshold = 1
    elif vertically_close:
        threshold = 0.7
    else:
        threshold = 0.85

    # Compute coherency threshold
    return ws_overlap_width / sum(ws.width for ws in ws_long) >= threshold


def _merge_section_whitespaces(sections: list[ColumnSection]) -> list[ColumnSection]:
    """
    Try merging consecutive column sections that have overlapping whitespaces.
    :param sections: List of column sections to merge.
    :return: Merged list of column sections.
    """
    if len(sections) <= 1:
        return sections

    # Compute common whitespaces across sections
    common_ws = sections[0].whitespaces
    for section in sections[1:]:
        _common_ws = []
        for ws in common_ws:
            matching_ws = [
                Whitespace(
                    start=max(ws.start, section_ws.start),
                    end=min(ws.end, section_ws.end),
                    start_bound=ws.start_bound and section_ws.start_bound,
                    end_bound=ws.end_bound and section_ws.end_bound,
                )
                for section_ws in section.whitespaces
            ]
            _common_ws += [m_ws for m_ws in matching_ws if m_ws.width > 0]
        common_ws = _common_ws

    return [
        ColumnSection(
            items=[it for section in sections for it in section.items],
            rows=[row for section in sections for row in section.rows],
            whitespaces=common_ws,
        )
    ]


def merge_column_sections(
    column_sections: list[ColumnSection], max_gap: float
) -> list[ColumnSection]:
    """
    Merge consecutive column sections that are close vertically if their whitespaces overlap.
    :param column_sections: List of column sections to merge.
    :param max_gap: Maximum vertical gap between sections to consider them close.
    :param min_width: Minimum width of a whitespace to be considered valid.
    :return: Merged list of column sections.
    """
    # Identify first section index with at least 2 columns
    first_section_with_columns = next(
        (idx for idx, sec in enumerate(column_sections) if sec.nb_columns >= 2), None
    )
    if first_section_with_columns is None:
        return column_sections

    # Create groups of columns that are close vertically
    merged_sections: list[ColumnSection] = column_sections[:first_section_with_columns]
    current_group: list[ColumnSection] = [column_sections[first_section_with_columns]]
    for section in column_sections[first_section_with_columns + 1 :]:
        if section.nb_columns < 2:
            # Flush current group
            merged_sections += _merge_section_whitespaces(sections=current_group)
            merged_sections.append(section)
            current_group = []
        elif len(current_group) == 0:
            current_group = [section]
        elif section.first_y_center - current_group[-1].last_y_center > max_gap:
            # Flush current group
            merged_sections += _merge_section_whitespaces(sections=current_group)
            current_group = [section]
        else:
            # Check coherency of whitespaces with previous section of the current group
            coherent = assess_table_whitespace_coherency(
                list_ws_1=current_group[-1].whitespaces,
                list_ws_2=section.whitespaces,
                vertically_close=(
                    section.first_y_center - current_group[-1].last_y_center <= 0.5 * max_gap
                ),
            )
            if coherent:
                current_group.append(section)
            else:
                # Flush current group and start a new one
                merged_sections += _merge_section_whitespaces(sections=current_group)
                current_group = [section]

    # Flush remaining group
    merged_sections += _merge_section_whitespaces(sections=current_group)

    return merged_sections


def _row_group_score(
    row_data: list[RowCharacteristic], index: int, max_gap: float, min_width: float
) -> int:
    """
    Count consecutive rows above and below `index` that have matching whitespaces.
    :param row_data: list of all row characteristics
    :param index: index of the candidate seed row
    :param max_gap: maximum vertical gap between consecutive rows
    :param min_width: minimum whitespace width for matching
    :return: number of consecutive matching neighbors in both directions
    """
    count = 0
    current_ws = row_data[index].ws
    for i in range(index + 1, len(row_data)):
        if abs(row_data[i].row.y_center - row_data[i - 1].row.y_center) > max_gap:
            break
        is_match, current_ws = matching_whitespaces(current_ws, row_data[i].ws, min_width)
        if not is_match:
            break
        count += 1

    current_ws = row_data[index].ws
    for i in range(index - 1, -1, -1):
        if abs(row_data[i + 1].row.y_center - row_data[i].row.y_center) > max_gap:
            break
        is_match, current_ws = matching_whitespaces(current_ws, row_data[i].ws, min_width)
        if not is_match:
            break
        count += 1

    return count


def compute_column_section(
    merged_rows: list[MergedRow], min_width: float, width: int, ratio_vertical_separation: float
) -> list[ColumnSection]:
    """
    Compute column sections from merged rows.
    :param merged_rows: list of merged rows
    :param min_width: minimum width for a whitespace to be considered
    :param width: total width of the section
    :param ratio_vertical_separation: ratio of median row separation to use as max vertical separation
    :return: list of column sections
    """
    # Compute median row separation
    row_separations = [nxt.y_center - prv.y_center for prv, nxt in pairwise(merged_rows)]
    median_row_separation = np.median(row_separations) if row_separations else 0
    max_gap = median_row_separation * ratio_vertical_separation

    # Compute all rows characteristics
    row_data = [
        RowCharacteristic(
            index=idx, row=row, ws=row.compute_whitespaces(min_width=min_width, width=width)
        )
        for idx, row in enumerate(merged_rows)
    ]

    # Pre-compute group scores: how many consecutive matching rows each row has above/below.
    group_scores = [_row_group_score(row_data, rd.index, max_gap, min_width) for rd in row_data]

    # Construct column sections by starting with the row with the most whitespaces and expanding upwards/downwards
    used_rows: set[int] = set()
    column_sections: list[ColumnSection] = []
    while len(used_rows) < len(merged_rows):
        # Check available rows
        available = [r for r in row_data if r.index not in used_rows]
        if not available:
            break

        # Get the row most likely to be the core of a table.
        seed = max(
            available,
            key=lambda x: ((x.count - 1) * (group_scores[x.index] + 1), x.inner_ws_width),
        )
        section = ColumnSection().update(row=seed.row, whitespaces=seed.ws)
        used_rows.add(seed.index)

        # Downwards expansion
        for row_idx in range(seed.index + 1, len(merged_rows)):
            if row_idx in used_rows:
                break
            target = row_data[row_idx]

            # Check vertical gap
            if abs(section.last_y_center - target.row.y_center) > max_gap:
                break

            # Check whitespace correspondence
            is_match, match_ws = matching_whitespaces(section.whitespaces, target.ws, min_width)
            if is_match:
                section.update(row=target.row, whitespaces=match_ws)
                used_rows.add(row_idx)
            else:
                break

        # Upwards expansion
        for row_idx in range(seed.index - 1, -1, -1):
            if row_idx in used_rows:
                break
            target = row_data[row_idx]

            # Check vertical gap
            if abs(section.first_y_center - target.row.y_center) > max_gap:
                break

            # Check whitespace correspondence
            is_match, match_ws = matching_whitespaces(section.whitespaces, target.ws, min_width)
            if is_match:
                section.update(row=target.row, whitespaces=match_ws)
                used_rows.add(row_idx)
            else:
                break

        # Check top / bottom elements of section to ensure consistency
        column_sections += ensure_section_bounds_consistency(
            section=section, min_width=min_width, width=width
        )

    column_sections.sort(key=lambda sec: sec.y1)

    # Attempt to merge column sections
    return merge_column_sections(column_sections=column_sections, max_gap=max_gap)
